# Para habilitar diagnostic logging de un runner
# se debe agregar un secreto
# ACTIONS_RUNNER_DEBUG to true
#
# Para habilitar logdebug logging
# se debe agregar un secreto
# ACTIONS_STEP_DEBUG to true.

name: GHA ci

on:
  push:
    branches:
      - 'master'
jobs:
  preparativos :
    runs-on: ubuntu-latest
    steps:        
      - 
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1.9.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          logout: true
      - 
        name: Build and push to Docker
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: jorgelts/ubuntu:20.04
